import {mkdir,rm,cp,writeFile} from 'node:fs/promises';
const pages={
  '':{key:'THE FARM, UNDER COMMAND',title:'Run the whole farm from one operating picture.',lead:'Field work, irrigation, crops, livestock, inputs, harvest and financial control—connected to live signals and built on a proven ERP engine.',image:'platform.png',section:'One farm. One system.',body:'Control every layer of the agricultural enterprise from one governed operating foundation.'},
  'agriculture-erp-platform':{key:'ONE FARM. ONE SYSTEM.',title:'Run the agricultural enterprise from one operating picture.',lead:'Connect field work, irrigation, crops, livestock, assets, inventory, people and finance on one governed ERP foundation.',image:'platform.png',section:'A platform that understands the whole farm',body:'Replace fragmented spreadsheets and disconnected tools with a single source of operational and financial truth.'},
  'farm-operations-management':{key:'FIELD OPERATIONS',title:'Turn every farm plan into controlled daily execution.',lead:'Plan work, assign teams, monitor irrigation, capture field activity and resolve exceptions before they become losses.',image:'operations.png',section:'The command layer for agricultural operations',body:'Give managers one clear operating picture while every team works in familiar farm language.'},
  'agricultural-finance-software':{key:'AGRICULTURAL FINANCE',title:'Know the true financial position of every operation.',lead:'Bring budgets, procurement, inventory, payroll, assets and accounting into the same agricultural control environment.',image:'finance.png',section:'Financial discipline rooted in farm reality',body:'See how every operational decision affects margin, working capital and cash—without waiting for month-end reconstruction.'},
  'agricultural-business-intelligence':{key:'EXECUTIVE INTELLIGENCE',title:'Give leadership the truth while there is still time to act.',lead:'Translate live operations and financial records into decision-ready performance, forecasts, risks and exceptions.',image:'intelligence.png',section:'Intelligence built on governed records',body:'Move from backward-looking reports to a current operating picture that supports management, boards and investors.'},
  'sustainable-farm-management':{key:'RESPONSIBLE PRODUCTION',title:'Make sustainability measurable, operational and defensible.',lead:'Connect water, inputs, land, livestock and compliance evidence to the records used to run the enterprise every day.',image:'sustainability.png',section:'Responsible agriculture without parallel paperwork',body:'Build credible sustainability and compliance records from normal operations rather than assembling claims after the fact.'}
};
const features=['Operational control','Financial governance','Assets and inventory','Workforce visibility','Approval workflows','Executive reporting'];
const nav=`<header><a class="brand" href="/"><b>↟</b><span>MASAPHOKATI<small>AGRICULTURE OS</small></span></a><nav><a href="/agriculture-erp-platform/">Platform</a><a href="/farm-operations-management/">Operations</a><a href="/agricultural-business-intelligence/">Intelligence</a><a href="/agricultural-finance-software/">Finance</a></nav><a class="outline" href="#demo">Book a demonstration</a></header>`;
const footer=`<footer><div><em>MASAPHOKATI AGRICULTURE OS</em><h2>The farm, under command.</h2></div><div class="links"><a href="/agriculture-erp-platform/">Platform</a><a href="/farm-operations-management/">Operations</a><a href="/agricultural-finance-software/">Finance</a><a href="/agricultural-business-intelligence/">Intelligence</a><a href="/sustainable-farm-management/">Sustainability</a></div><p>Enterprise agriculture technology by Siyabusa ERP · South Africa</p></footer>`;
const html=(slug,p)=>`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${p.title} | Masaphokati</title><meta name="description" content="${p.lead}"><link rel="canonical" href="https://farm.siyabusaerp.co.za/${slug}"><meta property="og:title" content="${p.title}"><meta property="og:description" content="${p.lead}"><meta property="og:image" content="/images/${p.image}"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/hero-fix.css"></head><body>${nav}<main><section class="hero" style="--hero:url('/images/${p.image}')"><div class="shade"></div><div class="copy"><em>${p.key}</em><h1>${p.title}</h1><p>${p.lead}</p><div class="actions"><a class="primary" href="#demo">Book a demonstration →</a><a class="secondary" href="/agriculture-erp-platform/">Explore the platform</a></div></div></section><section class="stats"><div><strong>One record</strong><span>Across every operation</span></div><div><strong>Live control</strong><span>From field to finance</span></div><div><strong>Built to expand</strong><span>Across farms and entities</span></div></section><section class="editorial"><div><em>BUILT FOR CONTROL</em><h2>${p.section}</h2></div><div><p class="lead">${p.body}</p><div class="grid">${features.map((x,i)=>`<article><small>0${i+1}</small><h3>${x}</h3><p>Connected records, clear ownership and management visibility from one operating foundation.</p></article>`).join('')}</div></div></section><section id="demo" class="demo"><em>START WITH THE PRESSURE POINTS</em><h2>See your agricultural enterprise in one operating picture.</h2><a class="primary" href="mailto:hello@siyabusaerp.co.za">Request a private demonstration →</a></section></main>${footer}</body></html>`;
await rm('dist',{recursive:true,force:true});await mkdir('dist/images',{recursive:true});await cp('images','dist/images',{recursive:true});await cp('style.css','dist/style.css');await cp('hero-fix.css','dist/hero-fix.css');
for(const [slug,p] of Object.entries(pages)){const dir=slug?`dist/${slug}`:'dist';await mkdir(dir,{recursive:true});await writeFile(`${dir}/index.html`,html(slug,p));}
