export const PRIME_SOURCES_HATTIES_PILOT = {
  profileVersion: '2026-08-29.1',
  dataStatus: 'demonstration_assumptions',
  organisation: {
    name: 'Prime Sources',
    role: 'Agricultural consulting and pilot operator',
  },
  farm: {
    code: 'PS-HATTIES-001',
    name: 'Prime Sources — Hatties Pilot Farm',
    country: 'Eswatini',
    region: 'Manzini',
    locality: 'Mankayane',
    latitude: -26.6833,
    longitude: 31.0833,
    sizeHectares: 6,
    type: 'mixed_horticulture',
    waterSource: 'storage_tank_and_pump',
  },
  field: {
    code: 'VEG-A1',
    name: 'Vegetable Block A1',
    sizeHectares: 1.2,
    irrigationType: 'drip',
    crop: 'Cabbage',
    variety: 'Pilot commercial variety — confirm before production',
    cropCycleStatus: 'growing',
  },
  irrigation: {
    pressureSensorCode: 'PS-A1-PRESSURE-01',
    flowMeterCode: 'PS-A1-FLOW-01',
    targetPressureMinBar: 2.2,
    targetPressureMaxBar: 2.8,
    expectedFlowMinLitresPerMinute: 90,
    persistenceMinutes: 10,
    minimumConsecutiveLowReadings: 3,
  },
  pilotScenario: {
    title: 'Low irrigation delivery to Vegetable Block A1',
    simulatedPressureBar: 1.7,
    simulatedFlowLitresPerMinute: 68,
    lowPressureDurationMinutes: 12,
    consecutiveLowReadings: 3,
    pumpRunning: true,
    irrigationScheduled: true,
    expectedOutcome: 'high-confidence irrigation incident and field inspection work order',
  },
  evidenceNotice: 'Farm size, crop, block and irrigation values are pilot assumptions. Mankayane locality is grounded in Prime Sources material; operational values must be replaced by measured or manager-approved data before production use.',
} as const;
